import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('UI explicita cancelamento, entrada inválida e recursos indisponíveis', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.match(source, /Opção inválida; nenhuma ação foi executada/);
  assert.match(source, /Análise cancelada; nenhum arquivo foi alterado/);
  assert.match(source, /Listar backups conhecidos e restaurar/);
  assert.match(source, /Restauração cancelada; nenhum arquivo foi alterado/);
  assert.match(source, /Nenhum relatório operacional disponível/);
  assert.match(source, /Nenhum log técnico disponível/);
  assert.match(source, /Invoke-SelfMinifierBridge/);
  assert.match(source, /StandardInput\.BaseStream/);
  assert.match(source, /Criar backup e sobrescrever os arquivos originais/);
  assert.match(source, /Preservar os arquivos originais e criar arquivos \.min/);
  assert.match(source, /Cancelar e voltar ao menu/);
  assert.match(source, /'1' \{ \[void\]\$script:TemporaryAdjustments\.Remove\('outputMode'\).*return \}/);
  assert.match(source, /'2' \{ \$script:TemporaryAdjustments\.outputMode = 'BackupESobrescreverOriginais'.*return \}/);
  assert.match(source, /'3' \{ \$script:TemporaryAdjustments\.outputMode = 'PreservarOriginaisECriarMinificados'.*return \}/);
  assert.doesNotMatch(source, /4\. Aplicar os ajustes desta execução/);
  assert.doesNotMatch(source, /risco da execução ainda não possui estimativa|EXECUTION_RISK_ALGORITHM_PENDING/);
  assert.match(source, /command = 'scan-analysis'; adjustments = \$Adjustments/);
  assert.match(source, /Invoke-ScanAnalysis \$script:TemporaryAdjustments/);
  assert.match(source, /command = 'execute'[\s\S]*adjustments = \$Adjustments[\s\S]*confirmationFingerprint = \$analysis\.execution\.confirmationFingerprint/);
  assert.doesNotMatch(source, /authorizeOverwriteConflicts|Invoke-Analyze/);
  assert.doesNotMatch(source, /Modo temporário \(vazio mantém o persistente/);
  const bytes = await readFile(new URL('../src/app/ui.ps1', import.meta.url));
  assert.deepEqual([...bytes.subarray(0, 3)], [0xEF, 0xBB, 0xBF]);
});

test('UI configurações expõe menu final, view V2 read-only e delega Comportamento ao editor persistente existente', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.match(source, /function Show-ConfigurationMenu/);
  assert.match(source, /1\. Origem do projeto/);
  assert.match(source, /2\. Tipos de arquivo/);
  assert.match(source, /3\. Exclusões/);
  assert.match(source, /4\. Perfil de minificação/);
  assert.match(source, /5\. Comportamento/);
  assert.match(source, /6\. Ver configuração atual/);
  assert.match(source, /0\. Voltar/);
  assert.match(source, /'4' \{ Show-ConfigurationMenu \}/);
  assert.match(source, /'5' \{ Invoke-PersistentConfiguration \}/);
  assert.match(source, /'6' \{ Show-CurrentConfiguration \}/);
  assert.match(source, /function Invoke-PersistentConfiguration/);
  assert.match(source, /command = 'update-output-mode'; outputMode = \$newMode; confirmed = \$true/);
  assert.match(source, /Nenhuma configuração foi alterada/);
  assert.match(source, /command = 'summary'/);
  assert.match(source, /\$config = \$summary\.configuration/);
  assert.match(source, /Origem do projeto \(PastaRaiz\):/);
  assert.match(source, /Tipos de arquivo \(TiposArquivo\):/);
  assert.match(source, /Perfil \(Perfil\):/);
  assert.match(source, /Comportamento de saída \(ModoSaida\):/);
  assert.match(source, /Pastas ignoradas:/);
  assert.match(source, /Arquivos ignorados:/);
  assert.match(source, /Nenhuma/);
  assert.match(source, /Nenhum/);
  assert.doesNotMatch(source, /Schema detectado:|não está no schema V2|schema -ne 'v2'/);
});

test('UI B1.2 expõe edição de origem e tipos de arquivo com confirmação numérica', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.match(source, /function Invoke-EditProjectRoot/);
  assert.match(source, /function Invoke-EditFileTypes/);
  assert.match(source, /'1' \{ Invoke-EditProjectRoot \}/);
  assert.match(source, /'2' \{ Invoke-EditFileTypes \}/);
  assert.match(source, /Origem atual:/);
  assert.match(source, /Informe a nova pasta do projeto/);
  assert.match(source, /Nova origem:/);
  assert.match(source, /1\. Salvar alteração/);
  assert.match(source, /command = 'update-configuration-v2'; projectRoot = \$entrada; confirmed = \$true/);
  assert.match(source, /command = 'update-configuration-v2'; fileTypes = \$novoValor; confirmed = \$true/);
  assert.match(source, /1\. CSS/);
  assert.match(source, /2\. JavaScript/);
  assert.match(source, /3\. CSS \+ JavaScript/);
  assert.match(source, /Tipos atuais:/);
  assert.match(source, /Novos tipos:/);
  assert.match(source, /Nenhuma configuração foi alterada/);
  assert.match(source, /'5' \{ Invoke-PersistentConfiguration \}/);
  assert.match(source, /'6' \{ Show-CurrentConfiguration \}/);
});

test('UI B1.3 expõe edição de exclusões com adição/remoção numerada', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.match(source, /function Invoke-EditExclusions/);
  assert.match(source, /function Invoke-EditIgnoredFolders/);
  assert.match(source, /function Invoke-EditIgnoredFiles/);
  assert.match(source, /function Add-ExclusionEntry/);
  assert.match(source, /function Remove-ExclusionEntry/);
  assert.match(source, /'3' \{ Invoke-EditExclusions \}/);
  assert.match(source, /1\. Pastas ignoradas/);
  assert.match(source, /2\. Arquivos ignorados/);
  assert.match(source, /3\. Ver exclusões atuais/);
  assert.match(source, /1\. Adicionar pasta/);
  assert.match(source, /2\. Remover pasta/);
  assert.match(source, /3\. Ver lista/);
  assert.match(source, /1\. Adicionar arquivo/);
  assert.match(source, /2\. Remover arquivo/);
  assert.match(source, /Informe a pasta relativa que deve ser ignorada\./);
  assert.match(source, /Informe o arquivo relativo que deve ser ignorado\./);
  assert.match(source, /Exemplo = 'node_modules'/);
  assert.match(source, /Exemplo = 'src\\config\.js'/);
  assert.match(source, /Exemplo: \$\(\$info\.Exemplo\)/);
  assert.match(source, /1\. Adicionar/);
  assert.match(source, /1\. Remover/);
  assert.match(source, /0\. Cancelar/);
  assert.match(source, /O valor já está configurado\./);
  assert.match(source, /Não há pastas ignoradas para remover\./);
  assert.match(source, /Não há arquivos ignorados para remover\./);
  assert.match(source, /Seleção inválida; nenhuma configuração foi alterada\./);
  assert.match(source, /command = 'update-configuration-v2'; confirmed = \$true/);
  assert.match(source, /\$request\[\$info\.Field\] = \$novaLista/);
});

test('UI B1.4 remove placeholders e adiciona perfil com confirmação numérica', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.doesNotMatch(source, /Interface e mensagens/);
  assert.doesNotMatch(source, /Pastas e dados do programa/);
  assert.doesNotMatch(source, /Restaurar configurações padrão/);
  assert.doesNotMatch(source, /não está disponível nesta etapa da implementação/);
  assert.doesNotMatch(source, /Show-ConfigNotAvailable/);
  assert.match(source, /function Invoke-EditProfile/);
  assert.match(source, /'4' \{ Invoke-EditProfile \}/);
  assert.match(source, /Perfil atual:/);
  assert.match(source, /Novo perfil:/);
  assert.match(source, /1\. Conservador/);
  assert.match(source, /2\. Padrão/);
  assert.match(source, /3\. Máximo/);
  assert.doesNotMatch(source, /Personalizado/);
  assert.match(source, /command = 'update-configuration-v2'; profile = \$novoPerfil; confirmed = \$true/);
  assert.match(source, /1\. Criar configuração/);
  assert.match(source, /1\. Salvar alteração/);
  assert.doesNotMatch(source, /Confirmar-Acao 'Criar a configuração a partir do modelo/);
  assert.doesNotMatch(source, /Confirmar-Acao 'Salvar esta configuração para as próximas execuções/);
});
