import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('UI explicita cancelamento, entrada inválida e recursos indisponíveis', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.match(source, /Opção inválida; nenhuma ação foi executada/);
  assert.match(source, /Execução cancelada; nenhum arquivo foi alterado/);
  assert.match(source, /Listar backups conhecidos e restaurar/);
  assert.match(source, /Restauração cancelada; nenhum arquivo foi alterado/);
  assert.match(source, /Nenhum relatório operacional disponível/);
  assert.match(source, /Nenhum log técnico disponível/);
  assert.match(source, /Invoke-SelfMinifierBridge/);
  assert.match(source, /StandardInput\.BaseStream/);
  assert.match(source, /Criar backup e sobrescrever os arquivos originais/);
  assert.match(source, /Preservar os arquivos originais e criar arquivos \.min/);
  assert.match(source, /Cancelar e voltar ao menu/);
  assert.match(source, /'1' \{ \[void\]\$script:TemporaryAdjustments\.Remove\('outputMode'\).*return \}/);
  assert.match(source, /'2' \{ \$script:TemporaryAdjustments\.outputMode = 'BackupESobrescreverOriginais'.*return \}/);
  assert.match(source, /'3' \{ \$script:TemporaryAdjustments\.outputMode = 'PreservarOriginaisECriarMinificados'.*return \}/);
  assert.doesNotMatch(source, /4\. Aplicar os ajustes desta execução/);
  assert.doesNotMatch(source, /risco da execução ainda não possui estimativa|EXECUTION_RISK_ALGORITHM_PENDING/);
  assert.match(source, /confirmationFingerprint = \$analysis\.confirmationFingerprint/);
  assert.match(source, /command = 'scan-analysis'; adjustments = \$Adjustments/);
  assert.match(source, /Invoke-ScanAnalysis \$script:TemporaryAdjustments/);
  assert.match(source, /command = 'execute'[\s\S]*adjustments = \$Adjustments[\s\S]*confirmationFingerprint = \$analysis\.execution\.confirmationFingerprint/);
  assert.match(source, /authorizeOverwriteConflicts = \$authorizeConflicts/);
  assert.doesNotMatch(source, /Modo temporário \(vazio mantém o persistente/);
  const bytes = await readFile(new URL('../src/app/ui.ps1', import.meta.url));
  assert.deepEqual([...bytes.subarray(0, 3)], [0xEF, 0xBB, 0xBF]);
});

test('UI configurações expõe menu, view V2 read-only e delega Comportamento ao editor persistente existente', async () => {
  const source = await readFile(new URL('../src/app/ui.ps1', import.meta.url), 'utf8');
  assert.match(source, /function Show-ConfigurationMenu/);
  assert.match(source, /1\. Origem do projeto/);
  assert.match(source, /2\. Tipos de arquivo/);
  assert.match(source, /3\. Exclusões/);
  assert.match(source, /4\. Comportamento/);
  assert.match(source, /5\. Interface e mensagens/);
  assert.match(source, /6\. Pastas e dados do programa/);
  assert.match(source, /7\. Ver configuração atual/);
  assert.match(source, /8\. Restaurar configurações padrão/);
  assert.match(source, /0\. Voltar/);
  assert.match(source, /'4' \{ Show-ConfigurationMenu \}/);
  assert.match(source, /'4' \{ Invoke-PersistentConfiguration \}/);
  assert.match(source, /'7' \{ Show-CurrentConfiguration \}/);
  assert.match(source, /function Invoke-PersistentConfiguration/);
  assert.match(source, /command = 'update-output-mode'; outputMode = \$newMode; confirmed = \$true/);
  assert.match(source, /não está disponível nesta etapa da implementação/);
  assert.match(source, /Nenhuma configuração foi alterada/);
  assert.match(source, /command = 'summary'/);
  assert.match(source, /\$config = \$summary\.configuration/);
  assert.match(source, /Origem do projeto \(PastaRaiz\):/);
  assert.match(source, /Tipos de arquivo \(TiposArquivo\):/);
  assert.match(source, /Comportamento de saída \(ModoSaida\):/);
  assert.match(source, /Pastas ignoradas:/);
  assert.match(source, /Arquivos ignorados:/);
  assert.match(source, /Nenhuma/);
  assert.match(source, /Nenhum/);
  assert.match(source, /Schema detectado:/);
  assert.match(source, /não está no schema V2/);
});
